export const helixFrames = [
  "helix-frames/frame-001.png",
  "helix-frames/frame-002.png",
  "helix-frames/frame-003.png",
  "helix-frames/frame-004.png",
  "helix-frames/frame-005.png",
  "helix-frames/frame-006.png",
  "helix-frames/frame-007.png",
  "helix-frames/frame-008.png",
  "helix-frames/frame-009.png",
  "helix-frames/frame-010.png",
  "helix-frames/frame-011.png",
  "helix-frames/frame-012.png",
  "helix-frames/frame-013.png",
  "helix-frames/frame-014.png",
  "helix-frames/frame-015.png",
  "helix-frames/frame-016.png",
  "helix-frames/frame-017.png",
  "helix-frames/frame-018.png",
  "helix-frames/frame-019.png",
  "helix-frames/frame-020.png",
  "helix-frames/frame-021.png",
  "helix-frames/frame-022.png",
  "helix-frames/frame-023.png",
  "helix-frames/frame-024.png",
  "helix-frames/frame-025.png",
] as const;
